### ISSUE TITLE
Feature request: Emoji replacement

### ISSUE THREAD

**Issue by yongjiajun** [forPelevin/gomoji#15]
Hi @forPelevin, thank you for maintaining the project.

I'm glad that I discovered this project as I find myself needing to work with emojis in Golang 😄 
However, one of my use cases involves replacing all emojis within a string with a given rune.

Since I've already worked on it on my [own fork](https://github.com/forPelevin/gomoji/compare/main...yongjiajun:gomoji:main), I'll open up a PR against the main branch to see what you think 👍

**Comment by forPelevin** [comment]
Hi @yongjiajun, thank you for the kind words. 

I really appreciate your contribution in the GoMoji project. Everything LGTM. The PR is merged and a new version released 😊
