### ISSUE TITLE
my go version dont support Generics

### ISSUE THREAD

**Issue by lovelydeng** [forPelevin/gomoji#17]
Hi ,I like your project, but it used Generics type, My project's go version is below 1.17.
so .what can I do..

**Comment by lovelydeng** [comment]
Hi  I think I can fork and change those strict array type to slice 
thank you

**Comment by forPelevin** [comment]
Hi @lovelydeng,

Thank you for the question.

Actually, Gomoji doesn't use Generics but our dependent libary `github.com/rivo/uniseg` does. So you can create an issue there and ask to avoid Generics.

Thank you.
