### ISSUE TITLE
Support for latest emoji release https://unicode.org/emoji/charts-14.0/emoji-released.html

### ISSUE THREAD

**Issue by AgrimPrasad** [forPelevin/gomoji#2]
Thanks for this library. It's very useful for detecting emojis in a fast and efficient manner.

This library is using the [emoji api](https://emoji-api.com/) which only supports Emojis up to v13.0 currently. Can we update it to support the latest release https://emojipedia.org/unicode-14.0/ too? Could possibly fetch the API and then statically add the new ones in `generator.go` until the Emoji API is updated for this?

Official release: https://unicode.org/emoji/charts-14.0/emoji-released.html

**Comment by forPelevin** [comment]
Hey! 

Thank you for the notice! I'll think about how we can update the emoji list up to v14.

**Comment by forPelevin** [comment]
Hello! 
I'm returning with great news. I've updated the emoji list, and now it's up to date. I parsed new emojis directly from https://unicode.org/emoji/charts/full-emoji-list.html.
Also, I moved the generator to another lib to avoid unnecessary dependencies here. 
Please, let me know if I can do anything else for you :)
