### ISSUE TITLE
ReplaceEmojisWithFunc: Unexpectedly trims strings

### ISSUE THREAD

**Issue by Mukhammadsaid19** [forPelevin/gomoji#21]
Function `ReplaceEmojisWithFunc` unexpectedly returns trimmed version of strings, thus modifying the original string. I would like to know the reason behind this, as it's not the responsibility of this function.

**Comment by forPelevin** [comment]
Hi @Mukhammadsaid19 ,

Thank you for the catch. I agree that trimming of spaces is not a responsibility of the replacer function so I fixed it in the PR: https://github.com/forPelevin/gomoji/pull/22
