### ISSUE TITLE
All numbers are judged as emoji 

### ISSUE THREAD

**Issue by ShawnOY** [forPelevin/gomoji#4]
Hi there,
I found if the string including any number, there will always return true, for example:

```golang
package main

import (
	"fmt"

	"github.com/forPelevin/gomoji"
)

func main() {
	fmt.Println(gomoji.ContainsEmoji("1"))
	// output: true

	fmt.Println(gomoji.ContainsEmoji("asdf1"))
	// output: true

	fmt.Println(gomoji.ContainsEmoji("asdf"))
	// output: false
}

```

**Comment by forPelevin** [comment]
Hey,

Thank you for the found bug. I'll fix it soon.

**Comment by forPelevin** [comment]
Hey,

[The release v1.1.1](https://github.com/forPelevin/gomoji/releases/tag/v1.1.1) has fixes for the issue. So please update the lib in your dependencies.

Thank you again for the report. It was beneficial for GoMoji. 

If you have anything else, please feel free to ask.
